shortenersite/urls.py
from django.urls import path,re_path
from . import views
app_name='shortenersite'
urlpatterns=[
    re_path(r'^$',views.index,name='home'),
    re_path(r'^(?P<short_id>\w{6})+?$', views.redirect_original,name='redirectoriginal'),
    re_path(r'^makeshort/$', views.shorten_url,name='shortenurl'),
]

urlshortener/urls.py
from django.contrib import admin
from django.urls import re_path,include

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'',include('shortenersite.urls'),name='shortenersite'),
]

shortenersite/models.py
from django.db import models

class Url(models.Model):
    shortid=models.SlugField(max_length=6,primary_key=True)
    orginalurl=models.URLField(max_length=200)

    def __str__(self):
        return self.orginalurl

shortenersite/views.py
from django.shortcuts import render, get_object_or_404
import random, string, json
from shortenersite.models import Url
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.core.checks.security import csrf

def index(request):
    return render(request,'shortenersite/index.html',{})


def redirect_original(request, short_id):
    url = get_object_or_404(Url, pk=short_id)  # get object, if not        found return 404 error
    return HttpResponseRedirect(url.orginalurl)

def shorten_url(request):
    url = request.POST.get("url", '')
    if not (url == ''):
        short_id = get_short_code()
        b = Url(orginalurl=url, shortid=short_id)
        b.save()
        response_data = {}
        response_data['url'] = settings.SITE_URL + "/" + short_id
        return HttpResponse(json.dumps(response_data),  content_type="application/json")
    return HttpResponse(json.dumps({"error": "error occurs"}), content_type="application/json")


def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    # if the randomly generated short_id is used then generate next
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        try:
            temp = Url.objects.get(pk=short_id)
        except:
            return short_id

shortenersite/templates/shortenersite/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
 <title>{% block title %}Welcome to mysite{% endblock %}</title>
 <link rel="stylesheet" href="{% static 'shortenersite/css/bootstrap.min.css' %}">
 <style>
     #content {
        margin-top: 20px;
        margin-bottom: 60px;
     }

     a:hover{
        text-decoration: none;
     }

     header {
        border-bottom: 1px solid #eeeeee;
        margin-bottom: 30px;
        padding-bottom: 10px;
        clear: both;
     }

     #wrap {
        max-width: 700px;
        margin: 5px 10px 10px 10px;
        padding: 10px;
        text-align: left;
     }
     #url-result {
        color: #00e000;
        display: hidden;
     }
 </style>

 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
 <meta name="viewport" content="width=device-width, initial-scale=1">

<script type="text/javascript">
 $(function() {
 $('#submitButton').click(function() {
 var patt=new RegExp(/\(?(?:(http|https|ftp):\/\/)?(?:((?:[^\W\s]|\.|-|[:]{1})+)@{1})?((?:www.)?(?:[^\W\s]|\.|-)+[\.][^\W\s]{2,4}|localhost(?=\/)|\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})(?::(\d*))?([\/]?[^\s\?]*[\/]{1})*(?:\/?([^\s\n\?\[\]\{\}\#]*(?:(?=\.)){1}|[^\s\n\?\[\]\{\}\.\#]*)?([\.]{1}[^\s\?\#]*)?)?(?:\?{1}([^\s\n\#\[\]]*))?([\#][^\s\n]*)?\)?/gi)
if($('#url').val()=="")
     $('#url-result').text("Do not submit blank.");
 else if(!patt.test($('#url').val()))
    $('#url-result').text("Make sure that you entered a valid URL");
 else{
 $.ajax({
 type: "POST",
 url: "/makeshort/",
 data: {
 'url' : $('#url').val(),
 'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
 },
 success: returnSuccess,
 dataType: 'json'
 });
}
 });
});

function returnSuccess(data, textStatus, jqXHR) {

 $('#url-result').text(data.url);
 $('#url').val("");


}
</script>
</head>

<body>

<div id="wrap">
<header>
 <h1><a href="{% url 'shortenersite:home' %}">URL Shortner</a><small>Shorten the URL</small></h1>
</header>
<div id="content">
{% block content %}

{% endblock %}
</div>
</div>
</body>
</html>

shortenersite/templates/shortenersite/index.html
{% extends "shortenersite/base.html" %}

{% block title %}URL Shortner - Make your URL shorter!{% endblock %}

{% block content %}

<div class="panel panel-default">
 <div class="panel-body">
 <div class="col-sm-9">
 <input type="text" name="url" id="url" class="form-control input-sm" placeholder="http://www.facebook.com" />
 </div>
 <div class="col-sm-3">
 {% csrf_token %}
 <button id="submitButton" class="btn btn-primary">Submit</button></p>
 </div>
 </div>
 <div class="panel-footer"><span id="url-result">Enter the URL above and click submit!</span></div>
</div>

{% endblock %}